### ISSUE TITLE
MILS/MELS API endpoints sometimes lack recent data

### ISSUE THREAD

**Issue by robin-leach** [elexon-data/insights-issues#1] opened 2023-05-10 13:49 UTC
## Describe the issue
Several times each week, the `/datasets/MELS` and `/datasets/MILS` will stop publishing the most up-to-date data. It can sometimes be around a day before they catch up, at which point the missing data is backfilled.

This **does not** affect data coming through IRIS, as new MILS/MELS files continue to be pushed through that service even when they are not being made available on the API endpoint.

## To Reproduce
This happened for example late on Monday 08/05/2023. So the following steps would have reproduced the issue for anyone trying them at 11:30pm BST, 08/05/2023

1. Make a GET HTTP request to https://data.elexon.co.uk/bmrs/api/v1/datasets/MELS?from=2023-05-08T22%3A00Z&to=2023-05-08T23%3A00Z&bmUnit=T_DRAXX-1, for example by visiting it in the broswer
2. Examine the response

## Expected behavior
The data should include MELS data for that BMU in that period:
```json
{
   "data":[
      {
         "dataset":"MELS",
         "settlementDate":"2023-05-09",
         "settlementPeriod":1,
         "timeFrom":"2023-05-08T23:00:00Z",
         "timeTo":"2023-05-08T23:30:00Z",
         "levelFrom":645,
         "levelTo":645,
         "notificationTime":"2023-05-04T10:00:02Z",
         "notificationSequence":102606550,
         "nationalGridBmUnit":"DRAXX-1",
         "bmUnit":"T_DRAXX-1"
      },
      {
         "dataset":"MELS",
         "settlementDate":"2023-05-08",
         "settlementPeriod":48,
         "timeFrom":"2023-05-08T22:30:00Z",
         "timeTo":"2023-05-08T23:00:00Z",
         "levelFrom":645,
         "levelTo":645,
         "notificationTime":"2023-05-04T10:00:02Z",
         "notificationSequence":102606550,
         "nationalGridBmUnit":"DRAXX-1",
         "bmUnit":"T_DRAXX-1"
      },
      {
         "dataset":"MELS",
         "settlementDate":"2023-05-08",
         "settlementPeriod":47,
         "timeFrom":"2023-05-08T22:00:00Z",
         "timeTo":"2023-05-08T22:30:00Z",
         "levelFrom":645,
         "levelTo":645,
         "notificationTime":"2023-05-04T10:00:02Z",
         "notificationSequence":102606550,
         "nationalGridBmUnit":"DRAXX-1",
         "bmUnit":"T_DRAXX-1"
      }
   ]
}
```

## Observed behavior

Instead, the response lacks any data:
```json
{
   "data":[]
}
```

## Additional context
- This is not specific to certain BMUs
- Because of the intermittent nature of this problem, and the fact that data is not exposed for a certain period but then correctly backfilled later, the above steps to reproduce are just demonstrative. Since the data has been backfilled you receive the correct data now, but this was not the case until the backfill was completed on Tuesday 09/05.

## Checks

Please answer the following questions for yourself before submitting an issue.

- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository
- [x] I'm reporting a problem and not a feature request
- [x] I have added the correct labels
- [x] I have added screenshots or other relevant evidence (if applicable)

**Comment by Samreay** [comment] 2023-05-22 06:04
In case its useful, I can report we've had a ton of failures this weekend. Are these issues caused by data coming in that breaks the normal schema, or is something else happening behind the scenes?

**Comment by robin-leach** [comment] 2023-06-05 16:23
> In case its useful, I can report we've had a ton of failures this weekend. Are these issues caused by data coming in that breaks the normal schema, or is something else happening behind the scenes?

Hi Sam, in this case the cause here is not a fault with receiving data or badly-formed data, but rather the process by which raw MILS/MELS files are combined to form the most up-to-date import/export limits for a BMU has reliability issues.

**Comment by Rob-Owen-Softwire** [comment] 2023-07-13 12:17
We have have deployed changes addressing both timeliness and correctness of resolved MILS/MELS datasets on the Insights API following extensive internal testing. These changes are live as of 13:10 (BST) today.

I'm closing this issue. Any future issues around MILS/MELS ought to be raised separately.

**Closed by Rob-Owen-Softwire** 2023-07-13 12:17 UTC
Labels: api, confirmed

**Comment by Samreay** [comment] 2023-07-13 12:31
Amazing, thanks @Rob-Owen-Softwire !
