### ISSUE TITLE
IRIS -  Error: Invalid Channel Number

### ISSUE THREAD

**Issue by Kim-Balmer** [elexon-data/insights-issues#14] opened 2023-07-05 10:28 UTC
James Stirton
Forefront.Energy 

We have been using the “new” IRIS API in parallel to the old one. We originally used the Python code in the Github repositiory. This worked fine. 
 
Now we see several an “Invalid Channel Number” error occurring. We checked with the code provided in Github and it also creates errors. 
 
Before we embark on a debug, I was wondering if anyone else had had these issues? 
 

This is using the exact code provided in Github.
 
As you can see, some messages are received and downloaded. The error “Invalid Channel Number” seems to then close the connection. The code then tries to reconnect and the loop continues. 
 
![image](https://github.com/elexon-data/insights-issues/assets/134283392/e302a680-ad4a-437f-a8eb-59f12fb8f728)

**Comment by Nkeokwelu** [comment] 2023-07-05 12:11
When a connection is established to the bus, the code retrieves a backlog of messages from the past three days. After a certain period, it pauses for approximately 10 minutes before resuming its operations. However, when we attempted to reinstall all the required modules, we discovered that three modules had not been installed previously. As a result, the code no longer pauses after every module has been installed. Nevertheless, it continues to send error messages as shown in the attached file below and also downloads files, such as the MID price, with a value of zero. Below is a screenshot of the MID displaying a zero value.


![error msg](https://github.com/elexon-data/insights-issues/assets/20742152/cf7274d6-482b-43f1-a0bc-efc2a52a24e6)

![zero value on MID](https://github.com/elexon-data/insights-issues/assets/20742152/b3d11c7b-e028-43af-92c6-aa4a255fb269)

**Comment by beccar97** [comment] 2023-09-21 09:04
I haven't been able to reproduce this issue unfortunately, I regularly use the example python IRIS client without issue. The IRIS client code are just examples, intended to help you create your own client, and aren't actively supported in the way that Insights itself is. I hope you're able to get your client working, but will close this ticket off.

**Closed by beccar97** 2023-09-21 09:04 UTC
